### ISSUE TITLE
[Feedback] Need Support

### ISSUE THREAD

**Issue by AraafRoyall** [Cai-Ming-Yu/CMY-CacheCleaner#1]
Hi. I am AraafRoyall 
I developed this [Cleaner Lite App](https://github.com/araafroyall/Cleaner-Pro-Lite)

I made this with Sketchware pro App.
And i dont know how to add xposed features like your app to clean something.
Can you help me with this how can i impliment xposed features in by using sketchware.
Or can we work together

**Comment by Cai-Ming-Yu** [comment]
I'm using https://github.com/HighCapable/YukiHookAPI for this app, but I don't have a lot of experience with it, so you can look at the documentation for it and copy my code into yours

**Comment by AraafRoyall** [comment]
But i want to use with sketchware pro.  No documentation is available for this

**Comment by Cai-Ming-Yu** [comment]
I don't know anything about this, but to use YukiHookAPI you just need to add kotlin and ksp, and then add the YukiHookAPI dependency

**Comment by AraafRoyall** [comment]
Ok..
But i can't use that as i want more simple method like block based as in sketchware pro.

Ok Thanks for the Reply. 
May i know you ? I mean your Gender , Country and Age 🙂

**Comment by Cai-Ming-Yu** [comment]
I've just been using xposed for a little while, I don't know much, and I've never used sketchware pro, so my abilities are limited, and the app I've written is very simple
It's a bit offensive to tell too much information, I'm in a country where the official language isn't English so I don't know much English so I generally use www.deepl.com for translations

**Comment by AraafRoyall** [comment]
Ok. Thnx . Nice to meet you. Baye take care

**Comment by AraafRoyall** [comment]
Can you give a try to my App and give Feedback or any idea about new features. 

Ok Anyway bYE ....
