### ISSUE TITLE
help me clean bing / edge cache..  not working

### ISSUE THREAD

**Issue by F3niIxX** [Cai-Ming-Yu/CMY-CacheCleaner#2]
Bing + edge makes like 2gb cache its terrible ..... this APP is a god sent to clean that but for some reason its not working , how do i send u logs or something like that to help fix it ?

**Comment by F3niIxX** [comment]
![Screenshot_20240201-123819_Configurações](https://github.com/Cai-Ming-Yu/CMY-CacheCleaner/assets/73638640/2289a07e-6065-47ae-9259-39543c484113)

**Comment by Cai-Ming-Yu** [comment]
There were some errors in the code, version 1.2.0 fixes the issues
